version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    volumes:
      - ./front-end:/app-frontend/
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3000']
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./back-end:/app-backend/
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev
    environment:
      - APP_PORT=3001
      - JWT_SECRET=secret_key
      - HOSTNAME=db
      - MYSQL_PORT=3306
      - MYSQL_DB_NAME=delivery-app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - NODE_ENV=development
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'unless-stopped'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE